version: '3'

services:
  app:
    build: 
      context: ./node
    image: lndaquino/node-desafio:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - mynet

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - mynet

  nginx:
    build: 
      context: ./nginx
    image: lndaquino/nginx-desafio:prod
    container_name: nginx
    networks:
      - mynet
    ports:
      - "8080:80"


networks:
  mynet:
    driver: bridge